/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.BD;
import DAO.Ficha;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Alexandre - Mail: asa-008@hotmail.com
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();

        setMinimumSize(new Dimension(1007, 823));

        URL CaminhoIcone = getClass().getResource("/Imagens/barra.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(CaminhoIcone);
        this.setIconImage(iconeTitulo);

        this.setLocationRelativeTo(this);

        Date now = new Date();
        txtData.setText(new SimpleDateFormat("dd/MM/yyyy").format(now));

        //configuração da tabela
        ((DefaultTableCellRenderer) TabLancamentos.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
        rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();
        rendererEsquerda.setHorizontalAlignment(SwingConstants.LEFT);

        JTableHeader header = TabLancamentos.getTableHeader();
        Font f = new Font("Arial", Font.BOLD, 12);
        header.setPreferredSize(new Dimension(0, 20));
        header.setBackground(Color.gray);
        header.setFont(f);

        header.setPreferredSize(new Dimension(0, 20));   // define a largura do cabeçalho
        header.setBackground(Color.gray);

        TableColumnModel mdCol = TabLancamentos.getColumnModel();

        mdCol.setColumnSelectionAllowed(false);

        mdCol.getColumn(0).setCellRenderer(rendererCentro);
        mdCol.getColumn(1).setCellRenderer(rendererCentro);
        mdCol.getColumn(2).setCellRenderer(rendererCentro);
        mdCol.getColumn(3).setCellRenderer(rendererCentro);
        mdCol.getColumn(4).setCellRenderer(rendererCentro);

        mdCol.getColumn(0).setMaxWidth(70);   //lançado
        mdCol.getColumn(1).setMaxWidth(90);   //lançado
        mdCol.getColumn(2).setMinWidth(90);   //tempo gasto
        mdCol.getColumn(3).setMinWidth(90);   //tempo gasto
        mdCol.getColumn(4).setMaxWidth(110);   //lançado
        
        TabLancamentos.setAutoCreateRowSorter(true);

        verificar();
    }

    public static boolean offline;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        txtValorTotal = new javax.swing.JFormattedTextField();
        jPanel16 = new javax.swing.JPanel();
        txtComissao = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtData = new javax.swing.JFormattedTextField();
        dcData = new datechooser.beans.DateChooserCombo();
        btnAtualizar = new javax.swing.JButton();
        painelNomeTarefa1 = new javax.swing.JPanel();
        txtResponsavel = new javax.swing.JTextField();
        painelNomeTarefa2 = new javax.swing.JPanel();
        txtAluno = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        txtValorTotal1 = new javax.swing.JFormattedTextField();
        painelNomeTarefa3 = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabLancamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Fichas 2.0");
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 128, 204)));
        jPanel1.setMaximumSize(getPreferredSize());
        jPanel1.setMinimumSize(getPreferredSize());

        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtValorTotal.setEditable(false);
        txtValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtValorTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValorTotal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtValorTotalCaretUpdate(evt);
            }
        });
        txtValorTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtValorTotalMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtValorTotal.getAccessibleContext().setAccessibleDescription("Valor total de vendas");

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comissão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtComissao.setEditable(false);
        txtComissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtComissao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComissao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtComissao.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtComissaoCaretUpdate(evt);
            }
        });
        txtComissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtComissaoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtComissao, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtComissao.getAccessibleContext().setAccessibleName("");
        txtComissao.getAccessibleContext().setAccessibleDescription("Total em comissão R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.getAccessibleContext().setAccessibleDescription("Total de horas trabalhadas no dia selecionado. Caso tenha batidas impares não calculará as horas trabalhadas.");
        jPanel16.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 128, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AlterarUsr.png"))); // NOI18N
        jLabel2.setText("Cadastro de Fichas 2.0");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setMaximumSize(getPreferredSize());
        jPanel3.setMinimumSize(getPreferredSize());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        dcData.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(51, 51, 51),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dcData.setCalendarBackground(new java.awt.Color(255, 255, 255));
    dcData.setFieldFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    dcData.setNavigateFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
    dcData.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dcDataOnSelectionChange(evt);
        }
    });

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dcData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2))
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dcData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 11, Short.MAX_VALUE))
    );

    btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
    btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            btnAtualizarMouseEntered(evt);
        }
    });
    btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAtualizarActionPerformed(evt);
        }
    });

    painelNomeTarefa1.setBackground(new java.awt.Color(255, 255, 255));
    painelNomeTarefa1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do Responsável", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
    painelNomeTarefa1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

    txtResponsavel.setBackground(new java.awt.Color(255, 255, 255));
    txtResponsavel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

    javax.swing.GroupLayout painelNomeTarefa1Layout = new javax.swing.GroupLayout(painelNomeTarefa1);
    painelNomeTarefa1.setLayout(painelNomeTarefa1Layout);
    painelNomeTarefa1Layout.setHorizontalGroup(
        painelNomeTarefa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(txtResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
    );
    painelNomeTarefa1Layout.setVerticalGroup(
        painelNomeTarefa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelNomeTarefa1Layout.createSequentialGroup()
            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 6, Short.MAX_VALUE))
    );

    painelNomeTarefa2.setBackground(new java.awt.Color(255, 255, 255));
    painelNomeTarefa2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do Aluno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
    painelNomeTarefa2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

    txtAluno.setBackground(new java.awt.Color(255, 255, 255));
    txtAluno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

    javax.swing.GroupLayout painelNomeTarefa2Layout = new javax.swing.GroupLayout(painelNomeTarefa2);
    painelNomeTarefa2.setLayout(painelNomeTarefa2Layout);
    painelNomeTarefa2Layout.setHorizontalGroup(
        painelNomeTarefa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(txtAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
    );
    painelNomeTarefa2Layout.setVerticalGroup(
        painelNomeTarefa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(painelNomeTarefa2Layout.createSequentialGroup()
            .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    btnIncluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Incluir.png"))); // NOI18N
    btnIncluir.setText("Incluir");
    btnIncluir.setMargin(new java.awt.Insets(2, 2, 2, 2));
    btnIncluir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnIncluirActionPerformed(evt);
        }
    });

    jPanel17.setBackground(new java.awt.Color(255, 255, 255));
    jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
    jPanel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

    txtValorTotal1.setEditable(false);
    txtValorTotal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
    txtValorTotal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtValorTotal1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtValorTotal1.addCaretListener(new javax.swing.event.CaretListener() {
        public void caretUpdate(javax.swing.event.CaretEvent evt) {
            txtValorTotal1CaretUpdate(evt);
        }
    });
    txtValorTotal1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            txtValorTotal1MouseEntered(evt);
        }
    });

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addComponent(txtValorTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
            .addGap(5, 5, 5))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addComponent(txtValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    painelNomeTarefa3.setBackground(new java.awt.Color(255, 255, 255));
    painelNomeTarefa3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
    painelNomeTarefa3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

    txtValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

    javax.swing.GroupLayout painelNomeTarefa3Layout = new javax.swing.GroupLayout(painelNomeTarefa3);
    painelNomeTarefa3.setLayout(painelNomeTarefa3Layout);
    painelNomeTarefa3Layout.setHorizontalGroup(
        painelNomeTarefa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
    );
    painelNomeTarefa3Layout.setVerticalGroup(
        painelNomeTarefa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(painelNomeTarefa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelNomeTarefa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelNomeTarefa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnIncluir))
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE)))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelNomeTarefa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnIncluir))
                                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelNomeTarefa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelNomeTarefa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275)))
    );

    TabLancamentos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    TabLancamentos.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "ID", "Data", "Nome Aluno", "Nome Responsável", "Valor"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    TabLancamentos.setColumnSelectionAllowed(true);
    TabLancamentos.getTableHeader().setReorderingAllowed(false);
    TabLancamentos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            TabLancamentosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(TabLancamentos);
    TabLancamentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(1, 1, 1))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        if (btnIncluir.getText().equals("Incluir")) {
            Ficha f = new Ficha();
            f.setData(txtData.getText());
            System.out.println(txtData.getText());
            f.setNome_aluno(txtAluno.getText());
            f.setNome_responsavel(txtResponsavel.getText());
            f.setValor(Double.parseDouble(txtValor.getText().replace(",", ".").replaceAll("[^0-9 | ^.]", "")));
            new BD().inserirFicha(f);
            verificar();
        } else {
            Ficha f = new Ficha();
            f.setId(ID);
            f.setData(txtData.getText());
            f.setNome_aluno(txtAluno.getText());
            f.setNome_responsavel(txtResponsavel.getText());
            f.setValor(Double.parseDouble(txtValor.getText().replace(",", ".").replaceAll("[^0-9 | ^.]", "")));
            new BD().alterarFicha(f);
            verificar();
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        verificar();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void dcDataOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dcDataOnSelectionChange
        txtData.setText(new SimpleDateFormat("dd/MM/yyyy").format(dcData.getSelectedDate().getTime()));
        verificar();
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_dcDataOnSelectionChange


    int ID;
    private void TabLancamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabLancamentosMouseClicked
        ID = Integer.parseInt(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 0).toString());
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_TabLancamentosMouseClicked

    private void txtValorTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorTotalMouseEntered

    }//GEN-LAST:event_txtValorTotalMouseEntered

    private void txtComissaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComissaoMouseEntered

    }//GEN-LAST:event_txtComissaoMouseEntered

    private void btnAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseEntered

    }//GEN-LAST:event_btnAtualizarMouseEntered

    private void txtValorTotalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtValorTotalCaretUpdate

    }//GEN-LAST:event_txtValorTotalCaretUpdate

    private void txtComissaoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtComissaoCaretUpdate

    }//GEN-LAST:event_txtComissaoCaretUpdate


    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Deseja realmente apagar a Ficha Selecionada?\n" + "<html><b><span style=\"color:RED\">OBS: A operação não poderá ser desfeita!!!</span></b></hmtl>", "Confirme", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {
            new BD().deletarFicha(ID);
            funcaoCancelar();
            verificar();
        } else if (i == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Operação Cancelada!!!", "Alerta!", 0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (btnAlterar.getText().equals("Alterar")) {
            btnAlterar.setText("Cancelar");
            btnAlterar.setIcon(icoCancelar);
            btnIncluir.setText("Alterar");
            btnIncluir.setIcon(icoAtrUsr);

            ID = Integer.parseInt(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 0).toString());
            txtData.setText(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 1).toString());
            txtAluno.setText(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 2).toString());
            txtResponsavel.setText(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 3).toString());
            txtValor.setText(TabLancamentos.getValueAt(TabLancamentos.getSelectedRow(), 4).toString());
        } else {
            btnAlterar.setText("Alterar");
            btnAlterar.setIcon(icoAlterar);
            btnIncluir.setText("Incluir");
            btnIncluir.setIcon(icoIncluir);
            funcaoCancelar();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtValorTotal1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtValorTotal1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotal1CaretUpdate

    private void txtValorTotal1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValorTotal1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotal1MouseEntered

   public void calcularComissao(){
       double total = new BD().buscarTotal();
       txtValorTotal.setText("R$ " + Double.toString(total));
       DecimalFormat df = new DecimalFormat("#.00");
       double comissao = total * 0.03;
       txtComissao.setText("R$ " + df.format(comissao));
   } 
    
    public void verificar() {
        limpar();
        funcaoCancelar();
        new BD().buscarFichas(TabLancamentos);
        calcularComissao();
    }

    public void funcaoCancelar() {
        limpar();
        btnAlterar.setText("Alterar");
        btnAlterar.setIcon(icoAlterar);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnIncluir.setText("Incluir");
        btnIncluir.setIcon(icoIncluir);
    }

    public void limpar() {
        txtAluno.setText("");
        txtResponsavel.setText("");
        txtValor.setText("");
    }

    Icon icoIncluir = new ImageIcon(TelaCadastro.class.getResource("/Imagens/Incluir.png"));
    Icon icoAtrUsr = new ImageIcon(TelaCadastro.class.getResource("/Imagens/AlterarUsr.png"));

    Icon icoCancelar = new ImageIcon(TelaCadastro.class.getResource("/Imagens/Cancelar.png"));
    Icon icoAlterar = new ImageIcon(TelaCadastro.class.getResource("/Imagens/Alterar.png"));

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabLancamentos;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private datechooser.beans.DateChooserCombo dcData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelNomeTarefa1;
    private javax.swing.JPanel painelNomeTarefa2;
    private javax.swing.JPanel painelNomeTarefa3;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JFormattedTextField txtComissao;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtValor;
    private javax.swing.JFormattedTextField txtValorTotal;
    private javax.swing.JFormattedTextField txtValorTotal1;
    // End of variables declaration//GEN-END:variables
}
